export type Finding={id:string;title:string;severity:string;engine:string;file:string;line:number;description:string;evidence:string;impact:string;remediation:string;confidence:number;cwe?:string;status:string;priority:string;risk?:number;simple?:string;source?:string};
export const demoFindings:Finding[]=[
{id:'demo-1',title:'Privileged credential exposed to the browser',severity:'Critical',engine:'Secrets',source:'Gitleaks',file:'src/lib/supabase.ts',line:14,description:'A service-role credential appears in a client-accessible module. This key can bypass row-level security.',evidence:'SUPABASE_SERVICE_ROLE_KEY = [REDACTED]',impact:'An attacker could read, change, or delete data with elevated permissions.',remediation:'Rotate the credential immediately. Remove it from frontend code and Git history. Move privileged operations to a trusted backend and review access logs.',confidence:0.98,cwe:'CWE-798',status:'open',priority:'Must Fix',simple:'A master key to your database is being shipped to every visitor. Replace the key and keep it on your server.'},
{id:'demo-2',title:'Potential authorization weakness in admin route',severity:'High',engine:'Authentication',source:'Auth pattern analysis',file:'app/api/admin/users/route.ts',line:8,description:'This administrative handler has no local role check. Shared middleware may protect it; review the surrounding authorization controls.',evidence:'Administrative handler detected; no local authorization guard found.',impact:'If no upstream guard exists, a regular user may access privileged operations.',remediation:'Verify the session on the server and enforce an administrator role before reading or modifying user records. Test access as anonymous and non-admin users.',confidence:0.65,cwe:'CWE-862',status:'open',priority:'Fix Soon',simple:'This admin door may be missing a lock. Check server-side permissions, including any shared middleware.'},
{id:'demo-3',title:'User input reaches an SQL query',severity:'High',engine:'Code',source:'Semgrep',file:'src/api/search.ts',line:23,description:'An SQL statement is constructed using request input. Review whether the database adapter parameterizes it.',evidence:'Query built through string interpolation; source omitted.',impact:'Untrusted input could change the meaning of the query.',remediation:'Use parameterized queries or the database client’s bound parameters. Validate input and restrict database privileges.',confidence:0.85,cwe:'CWE-89',status:'open',priority:'Must Fix',simple:'User input may be treated as database instructions. Pass it as a value using query parameters.'},
{id:'demo-4',title:'Dependency requires a security update',severity:'Medium',engine:'Dependencies',source:'OSV · illustrative finding',file:'package-lock.json',line:1,description:'Illustrative dependency advisory. Run a live scan for exact package versions and verified OSV identifiers.',evidence:'Sample dependency advisory — not a claim about this repository.',impact:'Impact depends on the advisory and how the dependency is used.',remediation:'Review the advisory, update to a fixed release, and run your application tests.',confidence:0.8,status:'open',priority:'Fix Soon'},
{id:'demo-5',title:'JWT payload decoded without local verification',severity:'Medium',engine:'Authentication',source:'Auth pattern analysis',file:'src/auth/session.ts',line:31,description:'A decode operation appears without signature verification in this file. Verification may occur upstream.',evidence:'jwt.decode(...)',impact:'Trusting an unverified token may allow identity claims to be modified.',remediation:'Verify the token signature, issuer, audience, and expiry with a maintained library before trusting claims.',confidence:0.6,cwe:'CWE-347',status:'open',priority:'Review'},
{id:'demo-6',title:'Weak hash used in a sensitive module',severity:'Low',engine:'Code',source:'Semgrep',file:'src/lib/hash.ts',line:5,description:'An MD5 hash is used. Confirm that this is not a password or integrity security control.',evidence:'createHash("md5")',impact:'MD5 is unsuitable for collision-resistant security checks.',remediation:'Use Argon2id for passwords or SHA-256 for appropriate integrity use cases.',confidence:0.7,cwe:'CWE-328',status:'open',priority:'Review'}];
export const stages=['Fetching repository','Detecting technology stack','Mapping project structure','Scanning source code','Checking credentials','Analyzing dependencies','Reviewing authentication logic','Correlating findings','Calculating deployment readiness'];
export const demoRepo={id:'demo',name:'launchpad-app',owner:'example-team',visibility:'private',default_branch:'main',language:'TypeScript',last_commit:'e8f3a2b',score:68,technologies:['Next.js','TypeScript','Supabase','PostgreSQL','Stripe']};
