'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {ReactFlow,Background,Controls,MarkerType,Node,Edge} from '@xyflow/react';
import {useReducedMotion} from 'framer-motion';
import {GitBranch,Network,ShieldCheck,History,ArrowUpRight,Download,RefreshCw,Maximize2,Minimize2} from 'lucide-react';
import {toast} from 'sonner';
import {RevisionsPanel} from './revisions';
import '@xyflow/react/dist/style.css';
type Request=(path:string,options?:RequestInit)=>Promise<any>;
const labels=['Overview','Security Graph','Attack Paths','Changes','Security Memory','Policies','PRs & Releases','Remediation','Team','Security Activity'];
const color=(severity:string)=>({Critical:'#ef777e',High:'#eda571',Medium:'#dfc679',Low:'#9ccab3'}[severity]||'#ab90bb');
function exportJSON(name:string,data:any){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
function SecurityGraph({graph,paths,diff,runtime}:{graph:any;paths:any[];diff:any;runtime:any}){
 const [selected,setSelected]=useState<any>(null),[mode,setMode]=useState('Security'),[type,setType]=useState('All'),[trace,setTrace]=useState('None'),[full,setFull]=useState(false);const reduced=useReducedMotion();
 const added=new Set((diff?.added_nodes||[]).map((n:any)=>n.id));
 const traced=useMemo(()=>{if(!selected||trace==='None')return null;const seen=new Set<string>([selected.id]);let queue=[selected.id];while(queue.length&&seen.size<250){const id=queue.shift();for(const e of graph.edges){const from=trace==='Upstream'?e.target:e.source,to=trace==='Upstream'?e.source:e.target;if(from===id&&!seen.has(to)){seen.add(to);queue.push(to)}}}return seen},[graph,selected,trace]);
 const pathIds=new Set(paths.flatMap(p=>p.node_ids));
 const graphNodes=mode==='Change'?[...graph.nodes,...(diff?.removed_nodes||[])]:graph.nodes;
 const visible=graphNodes.filter((n:any)=>(type==='All'||n.type===type)&&(!traced||traced.has(n.id))&&(mode!=='Attack Path'||pathIds.has(n.id))&&(mode!=='Change'||added.has(n.id)||(diff?.removed_nodes||[]).some((c:any)=>c.id===n.id)||(diff?.changed_nodes||[]).some((c:any)=>c.after.id===n.id)));
 const ids=new Set(visible.map((n:any)=>n.id));
 const nodes:Node[]=visible.map((n:any,i:number)=>({id:n.id,position:{x:(i%4)*230,y:Math.floor(i/4)*120},data:{label:<div className="life-node"><small>{n.type}</small><strong>{n.label}</strong>{n.severity&&<span>{n.severity}</span>}</div>},style:{border:`1px solid ${mode==='Change'?'#9ccab3':color(n.severity)}`,background:'#291b30',color:'#f8f4e9',width:200,borderRadius:12},ariaLabel:n.label}));
 const edges:Edge[]=graph.edges.filter((e:any)=>ids.has(e.source)&&ids.has(e.target)).map((e:any)=>({...e,type:undefined,label:e.type.replaceAll('_',' ').toLowerCase(),animated:!reduced&&mode==='Attack Path',style:{stroke:mode==='Attack Path'?'#eda571':'#935073'},labelStyle:{fill:'#dac5dc',fontSize:10},markerEnd:{type:MarkerType.ArrowClosed,color:'#935073'}}));
 return <section className={'panel life-graph '+(full?'life-fullscreen':'')}><div className="life-toolbar"><div className="life-tabs" aria-label="Graph view">{['Architecture','Security','Data Flow','Attack Path','Change','Runtime'].map(m=><button className={mode===m?'active':''} onClick={()=>setMode(m)} key={m}>{m}</button>)}</div><button className="btn secondary compact" aria-label="Toggle full screen" onClick={()=>setFull(!full)}>{full?<Minimize2 size={16}/>:<Maximize2 size={16}/>}</button></div><div className="life-toolbar"><label>Component type <select value={type} onChange={e=>setType(e.target.value)}>{['All',...Array.from(new Set(graph.nodes.map((n:any)=>n.type)))].map((t:any)=><option key={t}>{t}</option>)}</select></label><label>Trace from selected node <select value={trace} onChange={e=>setTrace(e.target.value)}>{['None','Upstream','Downstream'].map(t=><option key={t}>{t}</option>)}</select><span>{visible.length} nodes · {edges.length} relationships</span></label></div><p className="muted tiny">{mode==='Data Flow'?'Static connections only. Direction does not establish transfer of sensitive data.':mode==='Runtime'?(runtime?'Runtime observations are available below; they do not prove source execution.':'No runtime evidence for this scan.'):'Select a node to inspect evidence. No findings does not mean a component is healthy.'}</p><div className="life-canvas"><ReactFlow key={mode+type+trace+selected?.id} nodes={nodes} edges={edges} fitView minZoom={.1} maxZoom={2} nodesConnectable={false} onNodeClick={(_,n)=>setSelected(graphNodes.find((x:any)=>x.id===n.id))}><Background color="#6d476d"/><Controls/></ReactFlow></div>{selected&&<div className="life-inspector"><strong>{selected.label}</strong><span>{selected.type}</span><p>{selected.evidence}</p>{selected.file&&<code>{selected.file}:{selected.line}</code>}<p className="muted tiny">{selected.verification||'Static evidence; runtime behavior and authorization remain unverified.'}</p><button className="btn secondary compact" onClick={()=>{setSelected(null);setTrace('None')}}>Clear selection</button></div>}{mode==='Runtime'&&runtime&&<p>Observed {runtime.observations?.length||0} HTTP responses · Browser: {runtime.browser?.status||'Unavailable'} · Decision: {runtime.decision}</p>}</section>
}
export function LifecyclePanel({demo,repo,request,initialTab='Overview'}:{demo:boolean;repo:any;request:Request;initialTab?:string}){
 const [tab,setTab]=useState(initialTab),[list,setList]=useState<any[]>([]),[rid,setRid]=useState(repo?.id||''),[data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[activity,setActivity]=useState<any[]>([]),[members,setMembers]=useState<any[]>([]),[patches,setPatches]=useState<any[]>([]),[portfolio,setPortfolio]=useState<any>(null),[scanId,setScanId]=useState(''),[beforeId,setBeforeId]=useState(''),[policy,setPolicy]=useState<any>(null),[reason,setReason]=useState(''),[login,setLogin]=useState(''),[role,setRole]=useState('Viewer'),[token,setToken]=useState(''),[secretLabel,setSecretLabel]=useState('CI gate token'),[webhookPath,setWebhookPath]=useState('');
 const activeRepository=useRef(rid);activeRepository.current=rid;const requestSequence=useRef(0);
 useEffect(()=>{setTab(initialTab)},[initialTab]);
 useEffect(()=>{if(demo)return;let active=true;request('/api/lifecycle/repositories').then(r=>{if(active){setList(r);if(!rid)setRid(r[0]?.id||'')}}).catch(e=>setError(e.message));return()=>{active=false}},[demo]);
 async function load(){if(demo||!rid||activeRepository.current!==rid)return;const sequence=++requestSequence.current;setBusy(true);setData(null);setError('');setToken('');try{const query=new URLSearchParams();if(scanId)query.set('scan_id',scanId);if(beforeId)query.set('before_id',beforeId);const [a,b,c,d,p]=await Promise.all([request('/api/lifecycle/repositories/'+rid+'?'+query),request('/api/lifecycle/repositories/'+rid+'/activity'),request('/api/lifecycle/repositories/'+rid+'/members'),request('/api/lifecycle/repositories/'+rid+'/patches'),request('/api/lifecycle/portfolio')]);if(sequence!==requestSequence.current||activeRepository.current!==rid)return;setData(a);setPolicy(a.decision.policy);setActivity(b);setMembers(c);setPatches(d);setPortfolio(p)}catch(e){if(sequence===requestSequence.current&&activeRepository.current===rid){setData(null);setError((e as Error).message)}}finally{if(sequence===requestSequence.current&&activeRepository.current===rid)setBusy(false)}}
 useEffect(()=>{void load()},[rid,scanId,beforeId,demo]);
 const can=(p:string)=>data?.permissions?.includes(p);
 async function act(path:string,body:any){setBusy(true);try{const result=await request('/api/lifecycle/repositories/'+rid+path,{method:'POST',body:JSON.stringify(body)});toast.success(result.note||'Saved');await load();return result}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 if(demo)return <section className="panel life-empty"><Network size={36}/><div className="eyebrow">SECURITY LIFECYCLE</div><h2>Follow the evidence from commit to release.</h2><p>Connect the live scanner backend and a GitHub repository to build your security graph, compare scans, track recurring risks, and apply release policies.</p><p className="muted">No lifecycle history is fabricated from the sample diagnosis. Your existing preview remains available in the other sections.</p><div className="life-tabs">{labels.map(l=><span key={l}>{l}</span>)}</div></section>;
 return <div className="life-workspace"><div className="life-toolbar"><label>Repository <select value={rid} onChange={e=>{setRid(e.target.value);setScanId('');setBeforeId('')}}><option value="">Select repository</option>{list.map(r=><option value={r.id} key={r.id}>{r.name} · {r.role}</option>)}</select></label><button className="btn secondary compact" disabled={busy||!rid} onClick={load}><RefreshCw size={15}/>Refresh</button>{can('scan')&&<button className="btn compact" disabled={busy} onClick={async()=>{const branch=window.prompt('Branch to scan',data?.scan?.branch||'main');if(branch)await act('/scan',{branch})}}>Scan branch</button>}{rid&&<button className="btn secondary compact" onClick={async()=>{try{exportJSON('security-audit.json',await request('/api/lifecycle/repositories/'+rid+'/audit'))}catch(e){toast.error((e as Error).message)}}}><Download size={15}/>Audit export</button>}</div>{error&&<div className="panel" role="alert"><h3>Evidence unavailable</h3><p>{error}</p><p>Run a repository scan first, or check your access and backend configuration.</p></div>}{busy&&<p role="status">Loading repository evidence…</p>}{data&&<><div className="life-tabs" role="tablist">{labels.map(l=><button role="tab" aria-selected={tab===l} className={tab===l?'active':''} onClick={()=>setTab(l)} key={l}>{l}</button>)}</div><div className="life-context"><GitBranch size={15}/>{data.scan.branch} · {data.scan.commit?.slice(0,12)||'Commit unavailable'} · {data.role}<span>{new Date(data.scan.created_at).toLocaleString()}</span></div>
 {tab==='Overview'&&<><section className="panel life-decision"><div><div className="eyebrow">EVIDENCE + CONTEXT + POLICY</div><h2>{data.decision.decision}</h2><p>Security score {data.scan.score??'—'}/100 · Policy {data.decision.policy_revision.slice(0,12)}</p></div><ShieldCheck size={40}/><div className="life-reasons">{data.decision.blockers.map((b:any,i:number)=><p key={i}><strong>{b.rule.replaceAll('_',' ')}</strong> — {b.reason}</p>)}{data.decision.gaps.map((g:string)=><p key={g}>Evidence gap: {g}</p>)}</div></section><div className="three-grid">{[['Potential paths',data.paths.length],['Reintroductions',data.memory.patterns.reduce((n:number,p:any)=>n+p.reintroduced,0)],['Architecture changes',data.diff?data.diff.added_nodes.length+data.diff.removed_nodes.length:'No baseline']].map(([label,value])=><article className="panel" key={label}><small>{label}</small><h2>{value}</h2></article>)}</div><section className="panel"><h3>What should I fix first?</h3>{data.priorities.map((f:any)=><div className="life-row" key={f.id}><span className="life-risk" style={{color:color(f.severity)}}>{f.risk_score}</span><div><strong>{f.title}</strong><p>{f.priority_category} · {f.file}:{f.line}</p><details><summary>Why this priority?</summary>{f.risk_reasons.map((r:string)=><p key={r}>{r}</p>)}<p>Exploitability: {f.exploitability}. Authentication: {f.auth_requirement}.</p></details></div>{can('accept')&&<button className="btn secondary compact" onClick={async()=>{const r=window.prompt('Reason for accepting this risk (at least 10 characters). Policy blockers remain in effect.');if(r)await act('/triage',{scan_id:data.scan.id,finding_refs:[f.fingerprint],status:'accepted_risk',reason:r})}}>Accept risk</button>}</div>)}{!data.priorities.length&&<p>No findings in this assessment. Check coverage before releasing.</p>}</section></>}
 {tab==='Security Graph'&&<SecurityGraph graph={data.graph} paths={data.paths} diff={data.diff} runtime={data.runtime}/>}
 {tab==='Attack Paths'&&<><p className="muted">Potential paths use bounded graph traversal. A route/import association is not a confirmed exploit.</p>{data.paths.map((p:any,i:number)=><article className="panel life-path" key={i}><span className="badge high">{p.severity}</span><h3>{p.entry}</h3><div>{p.node_ids.map((id:string,j:number)=><span key={id}>{j>0&&<ArrowUpRight size={15}/>}<span>{data.graph.nodes.find((n:any)=>n.id===id)?.label}</span></span>)}</div><p>{p.note}</p></article>)}{!data.paths.length&&<section className="panel">No potential paths were established within supported analysis. This does not establish that vulnerabilities are unreachable.</section>}</>}
 {tab==='Changes'&&<><div className="life-toolbar"><label>Current assessment <select value={scanId||data.scan.id} onChange={e=>setScanId(e.target.value)}>{data.memory.timeline.slice().reverse().map((s:any)=><option key={s.scan_id} value={s.scan_id}>{s.commit?.slice(0,10)} · {s.score??'—'}</option>)}</select></label><label>Compare with <select value={beforeId} onChange={e=>setBeforeId(e.target.value)}><option value="">Previous assessment</option>{data.available_scans.filter((s:any)=>s.id!==data.scan.id).map((s:any)=><option key={s.id} value={s.id}>{s.branch} · {s.commit?.slice(0,10)} · {new Date(s.at).toLocaleDateString()}</option>)}</select></label></div>{data.diff?<section className="panel"><div className="eyebrow">{data.diff.impact} SECURITY CHANGE IMPACT</div><h2>{data.diff.regression?'Security regression detected':'Architecture comparison'}</h2><p>{data.diff.previous_score??'—'} → {data.diff.current_score??'—'} · {data.diff.comparable?'Comparable complete scans':'Comparison has coverage or branch differences'}</p><p>{data.diff.causality}</p>{[['Added',data.diff.added_nodes],['Removed',data.diff.removed_nodes]].map(([name,rows]:any)=><div key={name}><h3>{name} components ({rows.length})</h3>{rows.map((n:any)=><p key={n.id}>{n.type} · {n.label}</p>)}</div>)}<h3>Review these changes</h3>{data.diff.risks.map((r:any,i:number)=><p key={i}><strong>{r.kind}</strong> — {r.reason}</p>)}</section>:<section className="panel">Run a second assessment to compare architecture and security posture.</section>}</>}
 {tab==='Security Memory'&&<><section className="panel"><h3>Security health timeline</h3><p>{data.memory.scope}</p><div className="life-timeline">{data.memory.timeline.map((s:any)=><button key={s.scan_id} onClick={()=>{setScanId(s.scan_id);setTab('Overview')}}><strong>{s.score??'—'}</strong><span>{s.commit?.slice(0,8)}</span><small>{new Date(s.at).toLocaleDateString()}</small></button>)}</div></section>{data.memory.patterns.map((p:any)=><section className="panel" key={p.key}><span className="eyebrow">{p.reintroduced?'REINTRODUCED PATTERN':p.category}</span><h3>{p.title}</h3><p>{p.observations} observations · {p.occurrences} occurrence periods · {p.reintroduced} reintroductions</p><p>{p.file} · First {new Date(p.first_seen).toLocaleDateString()} · Last {new Date(p.last_seen).toLocaleDateString()}</p><p>State: {p.state.replaceAll('_',' ')}</p><p>{p.preventive_control}</p><small className="muted">Root cause: {p.root_cause}</small></section>)}</>}
 {tab==='Policies'&&policy&&<section className="panel life-form"><h3>Repository release policy</h3><p>Every revision is recorded. Incomplete evidence never produces an allowed release.</p><label>Minimum score <input type="number" min="0" max="100" disabled={!can('policy')} value={policy.minimum_score} onChange={e=>setPolicy({...policy,minimum_score:Number(e.target.value)})}/></label>{Object.keys(policy).filter(k=>k!=='minimum_score').map(k=><label key={k}><input type="checkbox" checked={!!policy[k]} disabled={!can('policy')} onChange={e=>setPolicy({...policy,[k]:e.target.checked})}/>{k.replaceAll('_',' ')}</label>)}<label>Reason for this revision <textarea value={reason} onChange={e=>setReason(e.target.value)} minLength={10}/></label><button className="btn compact" disabled={!can('policy')||reason.length<10||busy} onClick={()=>act('/policies',{...policy,reason})}>Save policy revision</button><hr/><h3>Continuous scans</h3><p>Configure a signed GitHub webhook for pushes, open or updated pull requests, merged pull requests and published releases on selected branches. Existing scan quotas apply.</p><button className="btn secondary compact" disabled={!can('policy')||busy} onClick={async()=>{const branch=window.prompt('Exact branch to monitor',data.scan.branch);if(branch){const r=await act('/webhook',{enabled:true,branches:[branch]});if(r){setSecretLabel('GitHub webhook secret');setWebhookPath(r.path);setToken(r.secret);toast.info('Webhook configured; copy the path and secret below')}}}}>Configure / rotate webhook</button><hr/><h3>CI/CD gate</h3><p>Use the included GitHub Actions integration. It checks the exact release commit and fails closed if evidence is missing. Creating a new token revokes the previous token.</p><button className="btn secondary compact" disabled={!can('policy')||busy} onClick={async()=>{const r=await act('/gate-tokens',{});if(r){setSecretLabel('CI gate token');setWebhookPath('');setToken(r.token)}}}>Rotate gate token</button>{webhookPath&&<p>Webhook endpoint on your backend: <code>{webhookPath}</code></p>}{token&&<label>{secretLabel} — copy once<input readOnly type="password" value={token} onFocus={e=>e.target.select()}/><button className="btn secondary compact" onClick={()=>navigator.clipboard.writeText(token).then(()=>toast.success('Copied')).catch(()=>toast.error('Select and copy the token manually'))}>Copy token</button></label>}{can('override')&&<><hr/><h3>Time-limited release override</h3><p>Owner/Admin only. Scoped to this assessment and policy revision for 24 hours; evidence gaps cannot be overridden.</p><button className="btn secondary compact" disabled={busy||data.decision.allowed||data.decision.gaps.length>0} onClick={async()=>{const r=window.prompt('Explain the release override (at least 10 characters):');if(r)await act('/overrides',{scan_id:data.scan.id,reason:r,finding_refs:data.decision.blockers.flatMap((b:any)=>b.finding_refs)})}}>Record override</button></>}</section>}
 {tab==='PRs & Releases'&&<RevisionsPanel rid={rid} request={request} act={act} allowed={can('scan')} busy={busy}/>}
 {tab==='Remediation'&&<><section className="panel"><h3>Review before changing code</h3><p>Automatic patches support advisory-listed version upgrades for exact Python requirements.txt pins. Application compatibility remains a developer review. No automatic authorization or business-logic edits.</p>{data.priorities.filter((f:any)=>f.engine==='Dependencies'&&f.file.endsWith('requirements.txt')).map((f:any)=><div className="life-row" key={f.id}><div><strong>{f.title}</strong><p>{f.remediation}</p></div><button className="btn compact" disabled={!can('remediate')||busy} onClick={async()=>{const version=window.prompt('Choose an advisory-listed fixed version: '+f.fixed_versions.join(', '));if(version)await act('/patches',{finding_id:f.id,version})}}>Generate patch</button></div>)}</section>{patches.map(p=><section className="panel" key={p.id}><h3>{p.path} · {p.version}</h3><p>{p.status.replaceAll('_',' ')} · {p.confidence}</p><pre>{p.diff}</pre><p>Validated: {p.validation.join('; ')}</p><p>Not validated: {p.not_validated.join('; ')}</p>{p.status==='review'&&<button className="btn compact" disabled={!can('remediate')||busy} onClick={async()=>{const r=window.prompt('After reviewing the patch, explain why it is appropriate. This creates a draft GitHub PR.');if(r)await act('/patches/'+p.id+'/pull-request',{reviewed:true,reason:r})}}>Review & create draft PR</button>}{p.pull_request_url&&<><a href={p.pull_request_url} target="_blank" rel="noreferrer" className="btn secondary compact">Open pull request</a><button className="btn secondary compact" disabled={!can('remediate')||busy} onClick={async()=>{const r=await act('/patches/'+p.id+'/verify',{});if(r)toast.info(r.status.replaceAll('_',' '))}}>Verify after merge</button></>}{p.status==='needs_reconciliation'&&<p>Check the recorded branch {p.draft_branch} on GitHub before retrying externally.</p>}</section>)}</>}
 {tab==='Team'&&<><section className="panel"><h3>Repository access</h3>{members.map(m=><div className="life-row" key={m.user_id}><strong>{m.login}</strong><span>{m.role}</span>{can('members')&&m.role!=='Owner'&&<button className="btn secondary compact" onClick={()=>act('/members/'+m.user_id+'/revoke',{})}>Revoke</button>}</div>)}{can('members')&&<div className="life-toolbar"><input aria-label="GitHub login" placeholder="Existing member’s GitHub login" value={login} onChange={e=>setLogin(e.target.value)}/><select aria-label="Repository role" value={role} onChange={e=>setRole(e.target.value)}>{['Admin','Security Lead','Developer','Viewer'].map(r=><option key={r}>{r}</option>)}</select><button className="btn compact" disabled={!login||busy} onClick={()=>act('/members',{login,role})}>Grant repository access</button></div>}</section>{portfolio&&<section className="panel"><h3>Accessible repository portfolio</h3><p>{portfolio.scope}</p>{portfolio.repositories.map((r:any)=><div className="life-row" key={r.repository.id}><strong>{r.repository.name}</strong><span>{r.decision.decision} · {r.critical} critical · {r.recurrences} reintroductions</span></div>)}<h3>Shared declared components</h3>{portfolio.shared_components.map((c:any)=><p key={c.type+c.label}>{c.label} · {c.repository_ids.length} repositories<br/><small>{c.association}</small></p>)}</section>}</>}
 {tab==='Security Activity'&&<section className="panel"><h3>Security activity</h3>{activity.map(a=><div className="life-row" key={a.id}><History size={18}/><div><strong>{a.kind.replaceAll('_',' ')}</strong><p>{new Date(a.at).toLocaleString()} · Actor {a.actor.slice(0,8)}</p><details><summary>Evidence</summary><pre>{JSON.stringify(a.data,null,2)}</pre></details></div></div>)}</section>}
 <p className="muted tiny">{data.graph.note} {data.graph.gaps.join(' · ')}</p></>}</div>
}
