'use client';
import {useEffect,useState} from 'react';
import {Globe,ShieldCheck,ArrowRight,ScanLine,RefreshCw,Download,Info,CheckCircle2,Server,LockKeyhole,Activity} from 'lucide-react';
import {motion,useReducedMotion} from './motion';

type RuntimeFinding={id:string;title:string;severity:string;path:string;evidence:string;remediation:string;priority:string};
type RuntimeReport={id:string;created_at:string;status:string;target_url:string;decision?:string;error?:string;findings?:RuntimeFinding[];observations?:{path:string;status:number;access:string}[];errors?:{path:string;reason:string}[];requests?:number;repository_assessment?:{id:string;status:string;decision:string;commit?:string;branch?:string};correlations?:{finding_id:string;title:string;path:string;status:number;evidence:string}[];coverage?:Record<string,string>;sample?:boolean};
const sample:RuntimeReport={id:'sample-runtime-001',sample:true,created_at:'2026-10-04T07:00:00Z',status:'completed',target_url:'https://staging.example.com/',decision:'NOT READY',requests:6,repository_assessment:{id:'sample-001',status:'completed',decision:'NOT READY',commit:'example',branch:'main'},observations:[{path:'/',status:200,access:'responded'},{path:'/api/profile',status:401,access:'protected'},{path:'/api/status',status:200,access:'responded'}],errors:[],correlations:[],findings:[{id:'cors',title:'Untrusted origin accepted by CORS',severity:'High',path:'/api/status',priority:'Must Fix',evidence:'Illustrative response allows the test origin with credentials. Sensitive-data exposure is not established.',remediation:'Use an explicit trusted-origin allowlist and review whether sensitive responses can be read.'},{id:'csp',title:'No enforced CSP response header observed',severity:'Medium',path:'/',priority:'Fix Soon',evidence:'Illustrative HTML response has no Content-Security-Policy header.',remediation:'Deploy a tested nonce/hash-based CSP. Report-only policies do not enforce restrictions.'},{id:'cookie',title:'Review cookie protection attributes',severity:'Low',path:'/',priority:'Review',evidence:'Illustrative cookie lacks SameSite. Cookie names and values are omitted.',remediation:'Choose an appropriate SameSite policy for the authentication flow.'}],coverage:{headers:'HTTP response rules',cookies:'Attributes only; values discarded',cors:'One untrusted-origin GET per path',routes:'User-selected, unauthenticated GET requests',browser:'Not implemented',cloud_configuration:'Not implemented',exploitability:'Not verified'}};
export function RuntimePanel({demo,repo,history,request}:{demo:boolean;repo:any;history:any[];request:(path:string,options?:RequestInit)=>Promise<any>}){
 const reduced=useReducedMotion();
 const [target,setTarget]=useState('');const [paths,setPaths]=useState('');const [authorized,setAuthorized]=useState(false);const [source,setSource]=useState('');
 const [reports,setReports]=useState<RuntimeReport[]>(demo?[sample]:[]);const [selected,setSelected]=useState<RuntimeReport|null>(demo?sample:null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [filter,setFilter]=useState('All');
 const baselines=history.filter(s=>['completed','partial'].includes(s.status));
 useEffect(()=>{setSource(baselines[0]?.id||'')},[repo?.id,history]);
 useEffect(()=>{let cancelled=false;setError('');setReports(demo?[sample]:[]);setSelected(demo?sample:null);if(!demo&&repo?.id)request('/api/repositories/'+repo.id+'/runtime-scans').then(rows=>{if(!cancelled){setReports(rows);setSelected(rows[0]||null)}}).catch(e=>{if(!cancelled)setError(e.message)});return()=>{cancelled=true}},[repo?.id,demo]);
 const running=selected&&['queued','running'].includes(selected.status);
 useEffect(()=>{if(!running||demo||!selected)return;let cancelled=false;let timer:ReturnType<typeof setTimeout>;const id=selected.id;async function poll(){try{const row=await request('/api/runtime-scans/'+id);if(cancelled)return;setError('');setSelected(row);setReports(old=>[row,...old.filter(r=>r.id!==id)]);if(['queued','running'].includes(row.status))timer=setTimeout(poll,2000)}catch(e){if(!cancelled){setError((e as Error).message);timer=setTimeout(poll,5000)}}}timer=setTimeout(poll,1000);return()=>{cancelled=true;clearTimeout(timer)}},[selected?.id,running,demo]);
 async function start(e:React.FormEvent){e.preventDefault();if(demo||busy||running)return;setBusy(true);setError('');try{const routes=paths.split('\n').map(x=>x.trim()).filter(Boolean);if(routes.length>5)throw new Error('Add up to five optional routes.');const row=await request('/api/repositories/'+repo.id+'/runtime-scans',{method:'POST',body:JSON.stringify({target_url:target.trim(),paths:routes,source_scan_id:source,authorized})});setSelected(row);setReports(old=>[row,...old]);setFilter('All')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function download(){if(!selected)return;const url=URL.createObjectURL(new Blob([JSON.stringify(selected,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=demo?'sample-launch-report.json':'launch-readiness-report.json';a.click();URL.revokeObjectURL(url)}
 const findings=selected?.findings||[];
 return <div className="runtime-workspace"><section className="runtime-intro panel"><div><div className="eyebrow">PHASE 2 · HTTP BASELINE</div><h2>See what your deployment exposes.</h2><p>Connect repository evidence to the response your users actually receive. Start with a bounded review of your staging environment.</p><div className="runtime-tags"><span><ShieldCheck size={14}/>Security headers</span><span><LockKeyhole size={14}/>Cookies & CORS</span><span><Server size={14}/>API responses</span></div></div><div className="runtime-orbit" aria-hidden="true"><motion.div className="orbit-ring" animate={reduced?{}:{rotate:360}} transition={{duration:40,repeat:Infinity,ease:'linear'}}><span/><span/></motion.div><Globe size={47}/><span className="orbit-caption">REPOSITORY → RUNTIME</span></div></section>
 <div className="runtime-layout"><section className="panel runtime-config"><div className="row"><h2><ScanLine size={19}/>New deployment check</h2></div>{demo?<><p className="muted">This is an illustrative report. No URL has been contacted.</p><div className="runtime-sample-target"><Globe size={18}/><span>staging.example.com<small>Sample environment</small></span></div><p className="tiny">Live checks become available when GitHub and the scan services are connected. Authorized hostnames are configured by the deployment operator.</p><button className="btn secondary full" onClick={()=>{setSelected(sample);setFilter('All')}}>Explore sample report <ArrowRight size={16}/></button></>:<form onSubmit={start}><label>Staging HTTPS URL<input type="url" required maxLength={500} placeholder="https://staging.your-app.com/" value={target} onChange={e=>setTarget(e.target.value)}/></label><label>Repository assessment<select value={source} onChange={e=>setSource(e.target.value)} required><option value="">Select a baseline scan</option>{baselines.map(s=><option value={s.id} key={s.id}>{s.branch||'Repository'} · {new Date(s.created_at).toLocaleDateString()} · {s.status}</option>)}</select></label><label>Optional API paths<textarea rows={4} value={paths} onChange={e=>setPaths(e.target.value)} placeholder={'/api/status\n/api/profile'}/><small>Up to five paths, one per line. No queries or state-changing endpoints.</small></label><label className="authorization-check"><input type="checkbox" checked={authorized} onChange={e=>setAuthorized(e.target.checked)} required/><span>I own this deployment or have permission to inspect it with GET requests.</span></label><button className="btn full" disabled={busy||!!running||!repo||!source||!authorized}>{busy||running?<RefreshCw size={16} className="spin"/>:<ScanLine size={16}/>} {running?'Check in progress':busy?'Starting…':'Run deployment check'}</button>{!baselines.length&&<p className="tiny">Run a repository scan first to establish the launch baseline.</p>}</form>}
 <div className="runtime-scope"><Info size={16}/><p>Public HTTPS only. Same deployment, selected paths, no sign-in cookies. Redirects are recorded without following them.</p></div></section>
 <div>{error&&<p className="panel error" role="alert">{error}</p>}{running?<section className="panel runtime-pending" role="status" aria-live="polite"><RefreshCw className="spin" size={30}/><h2>{selected?.status==='queued'?'Waiting for the worker':'Inspecting deployment responses'}</h2><p>Results are saved as the worker completes the assessment. You can return to this page later.</p></section>:selected?.error?<section className="panel"><h2>Assessment could not finish</h2><p className="error">{selected.error}</p><p>Review service health in Settings, then retry.</p></section>:selected?.decision?<section className="panel runtime-verdict"><div className="row"><div className="eyebrow">COMBINED LAUNCH REVIEW</div><span className="badge neutral">{demo?'Sample report':selected.status}</span></div><div className="row"><div><h2>{selected.decision}</h2><p>{selected.target_url}</p></div><button className="btn secondary compact" onClick={download} aria-label="Download launch report"><Download size={16}/>Export</button></div><div className="runtime-summary"><div><strong>{findings.filter(f=>f.priority==='Must Fix').length}</strong><span>Runtime must-fixes</span></div><div><strong>{selected.observations?.length||0}</strong><span>Paths reviewed</span></div><div><strong>{selected.errors?.length||0}</strong><span>Coverage gaps</span></div></div><div className="runtime-baseline"><GitBaseline/><span>Repository baseline: <strong>{selected.repository_assessment?.decision||'Incomplete'}</strong><small>{selected.repository_assessment?.branch||'Branch unknown'} · {selected.repository_assessment?.commit?.slice(0,8)||'Commit unavailable'} · Confirm this commit matches the staging deployment.</small></span></div></section>:<section className="panel empty"><Globe size={34}/><h3>Your first launch review starts here.</h3><p>Choose a repository assessment and inspect its staging deployment.</p></section>}
 <section className="panel runtime-coverage"><h2>What this release checks</h2>{[['HTTP headers, CSP & framing','Implemented'],['Cookie attributes & CORS','Implemented'],['Selected route responses','Implemented'],['Static route correlation','Basic mapping'],['Browser-driven analysis','Next increment'],['Cloud/BaaS configuration','Next increment']].map(([label,status])=><div key={label}><span>{label}</span><span className="badge neutral">{status}</span></div>)}<p className="tiny">Route responses do not prove an authentication bypass. The report does not verify exploitability.</p></section></div></div>
 {selected?.decision&&<><section className="panel"><div className="row"><h2>Runtime findings</h2><div className="runtime-filters" aria-label="Filter runtime findings">{['All','High','Medium','Low'].map(level=><button className={filter===level?'active':''} key={level} onClick={()=>setFilter(level)}>{level}</button>)}</div></div><div className="runtime-findings">{findings.filter(f=>filter==='All'||f.severity===filter).map(f=><details key={f.id}><summary><span className={'badge '+f.severity.toLowerCase()}>{f.severity}</span><span><strong>{f.title}</strong><small>{f.path} · {f.priority}</small></span><ArrowRight size={17}/></summary><div className="runtime-evidence"><h3>Observed evidence</h3><p>{f.evidence}</p><h3>Recommended action</h3><p>{f.remediation}</p></div></details>)}{!findings.filter(f=>filter==='All'||f.severity===filter).length&&<p className="muted">No matching findings in the performed checks.</p>}</div></section>
 <div className="two-grid"><section className="panel"><h2>Deployment exposure</h2>{selected.observations?.map(o=><div className="runtime-route" key={o.path}><code>{o.path}</code><span className="badge neutral">{o.status}</span><span>{o.access}</span></div>)}<p className="tiny">“Protected” means a 401/403 response was observed. A 200 response may be intentionally public.</p>{selected.errors?.map((e,i)=><p className="runtime-gap" key={i}>{e.path}: {e.reason}</p>)}</section><section className="panel"><h2>Repository → runtime context</h2>{selected.correlations?.length?selected.correlations.map((c,i)=><div className="runtime-correlation" key={i}><strong>{c.title}</strong><small>{c.path} · HTTP {c.status}</small><p>{c.evidence}</p></div>):<p>No exact supported static-route matches in this assessment. Dynamic routes and cross-file call paths require further analysis.</p>}<div className="subtle-note"><Info size={16}/>Runtime results supplement the saved repository scan; they never rewrite its score.</div></section></div></>}
 <section className="panel"><div className="row"><h2>Deployment check history</h2><span className="badge neutral">{reports.length} assessments</span></div>{reports.map(r=><button className="runtime-history" key={r.id} disabled={!!running&&r.id!==selected?.id} onClick={()=>{setSelected(r);setFilter('All')}}><CheckCircle2 size={19}/><span><strong>{r.target_url}</strong><small>{new Date(r.created_at).toLocaleString()} · {r.status}</small></span><span className="badge neutral">{r.decision||r.status}</span><ArrowRight size={16}/></button>)}{!reports.length&&<p className="muted">Saved deployment checks will appear here.</p>}</section></div>
}
function GitBaseline(){return <Activity size={19}/>}

export function ServiceStatus({api,request}:{api:string;request:(p:string)=>Promise<any>}){const [status,setStatus]=useState<any>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);async function check(){setBusy(true);setError('');try{setStatus(await request('/api/system/status'))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}return <div className="service-status"><h2>Connection diagnostics</h2><p>{api?'Check the database, queue, worker and OAuth configuration.':'The preview has no backend connection configured. Deploy the services and configure OAuth to enable real repository and runtime scans.'}</p>{api&&<button className="btn secondary compact" onClick={check} disabled={busy}><RefreshCw size={15} className={busy?'spin':''}/>{busy?'Checking…':'Check services'}</button>}{error&&<p className="error" role="alert">{error}</p>}{status&&<div className="service-grid">{Object.entries(status.checks).map(([name,ready])=><div key={name}><span>{name.replaceAll('_',' ')}</span><span className={'badge '+(ready?'neutral':'high')}>{ready?'Connected':'Needs setup'}</span></div>)}<div><span>Runtime target allowlist</span><span className="badge neutral">{status.runtime_hosts_configured?'Configured':'Needs setup'}</span></div></div>}</div>}
